import type { ToolDefinition, ToolContext, ToolResult } from '@jean2/sdk';

interface DiscordEmbedField {
  name: string;
  value: string;
  inline?: boolean;
}

interface DiscordEmbed {
  title?: string;
  description?: string;
  url?: string;
  color?: number;
  fields?: DiscordEmbedField[];
  footer?: { text: string };
  timestamp?: string;
  thumbnail?: { url: string };
  image?: { url: string };
  author?: { name: string; icon_url?: string; url?: string };
}

interface SendMessageInput {
  channelId?: string;
  content?: string;
  embeds?: DiscordEmbed[];
  username?: string;
  avatarUrl?: string;
  tts?: boolean;
}

const DISCORD_API_BASE = 'https://discord.com/api/v10';

export const definition: ToolDefinition = {
  name: 'discord-send-message',
  description: 'Send a message to a Discord channel via bot token. Supports plain text content and rich embeds.\n\nWhen to use:\n- Sending notifications, announcements, or changelogs to a Discord channel\n- Posting formatted content using Discord embeds (titles, descriptions, fields, colors, footers)\n- Delivering AI-generated summaries or reports to a Discord server\n\nWhen NOT to use:\n- Reading or searching messages (use discord-read-messages instead)\n- Managing channels, roles, or members\n- Sending direct messages to users\n\nParameters:\n- channelId (optional): The Discord channel ID to send to. Falls back to DISCORD_DEFAULT_CHANNEL_ID env var if not provided.\n- content (optional): Plain text message content (max 2000 characters). Required if embeds is not provided.\n- embeds (optional): Array of Discord embed objects for rich formatting. See embed structure below. Max 10 embeds.\n- username (optional): Override the bot\'s display name for this message (webhook-only, ignored for bot tokens)\n- avatarUrl (optional): Override the bot\'s avatar for this message (webhook-only, ignored for bot tokens)\n- tts (optional): If true, message is sent as text-to-speech\n\nEmbed structure:\n```\n{\n  title: "Server v1.0.13",\n  description: "Brief summary",\n  color: 5814333,  // RGB as integer (0x58ACDD = 5814333)\n  url: "https://...",\n  fields: [\n    { name: "Added", value: "- Feature A\\n- Feature B", inline: false },\n    { name: "Fixed", value: "- Bug fix description", inline: false }\n  ],\n  footer: { text: "Generated by Jean2" },\n  timestamp: "2024-01-15T00:00:00.000Z"\n}\n```\n\nNotes:\n- Color values are RGB integers (e.g. green = 5763719, red = 15548997, blue = 5814333)\n- Embed field values support markdown formatting\n- Total embed payload must not exceed 6000 characters\n- Requires a Discord bot token set as DISCORD_BOT_TOKEN env var\n- The bot must have SEND_MESSAGES permission in the target channel\n- To find channel/guild IDs, enable Developer Mode in Discord (Settings > Advanced > Developer Mode), then right-click a channel/server and select "Copy ID"',
  inputSchema: {
    type: 'object',
    properties: {
      channelId: {
        type: 'string',
        description: 'Discord channel ID to send the message to. Falls back to DISCORD_DEFAULT_CHANNEL_ID env var.',
      },
      content: {
        type: 'string',
        description: 'Plain text message content (max 2000 characters). Required if embeds is not provided.',
      },
      embeds: {
        type: 'array',
        description: 'Array of Discord embed objects for rich formatting (max 10).',
        items: {
          type: 'object',
          properties: {
            title: { type: 'string', description: 'Embed title (max 256 characters)' },
            description: { type: 'string', description: 'Embed description (max 4096 characters)' },
            url: { type: 'string', description: 'URL for the embed title' },
            color: { type: 'integer', description: 'RGB color as integer (e.g. 5814333 for blue)' },
            fields: {
              type: 'array',
              description: 'Embed fields (max 25)',
              items: {
                type: 'object',
                properties: {
                  name: { type: 'string', description: 'Field name (max 256 characters)' },
                  value: { type: 'string', description: 'Field value (max 1024 characters)' },
                  inline: { type: 'boolean', description: 'Whether fields should display inline (default false)' },
                },
                required: ['name', 'value'],
              },
            },
            footer: {
              type: 'object',
              description: 'Embed footer',
              properties: {
                text: { type: 'string', description: 'Footer text (max 2048 characters)' },
              },
            },
            timestamp: { type: 'string', description: 'ISO8601 timestamp for the embed' },
            thumbnail: {
              type: 'object',
              description: 'Thumbnail image',
              properties: {
                url: { type: 'string', description: 'Thumbnail image URL' },
              },
            },
            image: {
              type: 'object',
              description: 'Large image',
              properties: {
                url: { type: 'string', description: 'Image URL' },
              },
            },
            author: {
              type: 'object',
              description: 'Author block',
              properties: {
                name: { type: 'string', description: 'Author name' },
                icon_url: { type: 'string', description: 'Author icon URL' },
                url: { type: 'string', description: 'Author URL' },
              },
            },
          },
        },
      },
      username: {
        type: 'string',
        description: 'Override display name (webhook-only, ignored for bot tokens)',
      },
      avatarUrl: {
        type: 'string',
        description: 'Override avatar (webhook-only, ignored for bot tokens)',
      },
      tts: {
        type: 'boolean',
        description: 'Send as text-to-speech message',
      },
    },
  },
  timeout: 30000,
  env: [
    'DISCORD_BOT_TOKEN',
    'DISCORD_DEFAULT_CHANNEL_ID',
  ],
};

export async function execute(input: SendMessageInput, ctx: ToolContext): Promise<ToolResult> {
  try {
    if (!input.content && !input.embeds?.length) {
      return { success: false, error: 'Either content or embeds must be provided' };
    }

    const token = ctx.env.require('DISCORD_BOT_TOKEN');
    const channelId = input.channelId || ctx.env.get('DISCORD_DEFAULT_CHANNEL_ID');

    if (!channelId) {
      return {
        success: false,
        error: 'No channel ID provided. Set channelId parameter or DISCORD_DEFAULT_CHANNEL_ID env var.',
      };
    }

    const body: Record<string, unknown> = {};

    if (input.content) body.content = input.content;
    if (input.embeds?.length) body.embeds = input.embeds;
    if (input.username) body.username = input.username;
    if (input.avatarUrl) body.avatar_url = input.avatarUrl;
    if (input.tts !== undefined) body.tts = input.tts;

    let response: Response;
    try {
      response = await ctx.fetch(`${DISCORD_API_BASE}/channels/${channelId}/messages`, {
        method: 'POST',
        headers: {
          'Authorization': `Bot ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });
    } catch (fetchErr: unknown) {
      const msg = fetchErr instanceof Error ? fetchErr.message : String(fetchErr);
      return { success: false, error: `Failed to reach Discord API: ${msg}` };
    }

    let responseBody: unknown;
    try {
      responseBody = await response.json();
    } catch {
      return {
        success: false,
        error: `Discord API error (${response.status}): unexpected response format`,
      };
    }

    if (!response.ok) {
      const errorMsg = extractDiscordError(responseBody, response.status);
      return { success: false, error: errorMsg };
    }

    const message = responseBody as { id: string; channel_id: string };

    return {
      success: true,
      result: {
        messageId: message.id,
        channelId: message.channel_id,
        url: `https://discord.com/channels/@me/${message.channel_id}/${message.id}`,
      },
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    ctx.logger.error(`discord-send-message failed: ${message}`);
    return { success: false, error: message };
  }
}

function extractDiscordError(body: unknown, status: number): string {
  if (
    body &&
    typeof body === 'object' &&
    'message' in body &&
    typeof (body as { message: unknown }).message === 'string'
  ) {
    const discordError = body as { message: string; code?: number; errors?: unknown };
    let msg = `Discord API error (${status}): ${discordError.message}`;
    if (discordError.code !== undefined) {
      msg += ` [code: ${discordError.code}]`;
    }
    return msg;
  }
  return `Discord API error (${status})`;
}
